// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbGZ8B9Z3A81Rhe_bIXIRNYz1CJolBFLM',
    appId: '1:904492496991:android:ca4ec9ac217e6e09cf43ea',
    messagingSenderId: '904492496991',
    projectId: 'flutter-twitter-app-v2',
    databaseURL: 'https://flutter-twitter-app-v2-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-twitter-app-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvviTG4rXv_QVJIMt6W1T25OO9f-OIkzw',
    appId: '1:904492496991:ios:59929357b87edf4dcf43ea',
    messagingSenderId: '904492496991',
    projectId: 'flutter-twitter-app-v2',
    databaseURL: 'https://flutter-twitter-app-v2-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-twitter-app-v2.appspot.com',
    iosClientId: '904492496991-07gg9iarqhs7ph0p5uqiiffe605t2c0v.apps.googleusercontent.com',
    iosBundleId: 'com.haluuvananh.twitter.twitter',
  );
}
